site_name: openEHR CDR API for client-side developers (DHCW)
docs_dir: mkdocs
nav:
    - Overview: 'README.md'
    - Introduction to openEHR:
        - 'intro/INT1-overview-openehr.md'
        - 'intro/INT2-overview-rest-apis.md'
        - 'intro/INT3-archetypes-template.md'
        - 'intro/INT4-reference-model.md'
        - 'postman/PM1-postman-getting-ready.md'
        - 'postman/PM2-navigate-postman.md'
        - 'postman/PM3-using-postman.md'
    - Jamaica Passport project:
        - 'passport/JPASS1-passport-project-overview.md'
        - 'passport/JPASS2-retrieving-an-ehrid.md'
        - 'passport/JPASS3-querying-allergies.md'
        - 'passport/JPASS7-querying-compositions.md'
        - 'passport/JPASS9-committing-observation-data.md' 
        - 'passport/JPASS10-retrieving-observation-data.md'
        - 'passport/JPASS11-updating-observation-data.md'
        - 'passport/JPASS12-composition-constraints.md'
        - 'passport/JPASS13-openehr-datatypes.md'
        - 'passport/JPASS14-openehr-rm-attributes.md'
    - openCDR API:
        - 'opencdr/OCDR1-authentication.md'
        - 'opencdr/OCDR2-openehr-templates.md'
        - 'opencdr/OCDR3-committing-a-composition.md'
        - 'opencdr/OCDR4-retrieving-a-composition.md'
        - 'opencdr/OCDR5-creating-an-ehr.md'
        - 'opencdr/OCDR6-retrieving-an-ehrid.md'    
    - Better Ehrscape API:
        - 'ehrscape/ECDR1-authentication.md'
        - 'ehrscape/ECDR2-openehr-templates.md'
        - 'ehrscape/ECDR3-committing-a-composition.md'
        - 'ehrscape/ECDR4-retrieving-a-composition.md'
        - 'ehrscape/ECDR5-retrieving-an-ehrId.md'
        - 'ehrscape/ECDR6-updating-a-composition.md'

plugins:
    - search
    - macros                  
theme:
  name: material
  logo: images/NWISWalesNHSUK2.png
  favicon: images/NWISWalesNHSUK2.png
  palette:
    primary: blue grey
    accent: teal 
markdown_extensions:
  - toc:
      toc_depth : "1-1"
  - admonition
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde 
  - codehilite
extra:    
    name: 'DHCW'
    cdr:
      authToken: 'Basic YTgxZjQ3YzYtYTc1Ny00ZTM0LWI2NDQtM2NjYzYyYjRhMDFjOiQyYSQxMCQ2MTlraQ=='
      subjectNamespace: 'uk_nhs_nhs_number'
      ehrscapeBaseUrl: 'https://rest.ehrscape.com/rest/v1'
      opencdrBaseUrl: 'https://rest.ehrscape.com/rest/openehr/v1'
      queryString: 'SELECT ... FROM ... CONTAINS ... WHERE'
      postmanLink: '(https://app.getpostman.com/run-collection/20729-17be3698-fb0b-4f4d-82c2-a128efa9c29c?action=collection%2Ffork&collection-url=entityId%3D20729-17be3698-fb0b-4f4d-82c2-a128efa9c29c%26entityType%3Dcollection%26workspaceId%3Db92254b2-1f5c-4442-8595-21165204e9dc#?env%5BDHCW%20Training%20CDR%5D=W3sia2V5IjoiY2RyUHJvZHVjdCIsInZhbHVlIjoiQmV0dGVyIiwiZW5hYmxlZCI6dHJ1ZSwic2Vzc2lvblZhbHVlIjoiQmV0dGVyIiwic2Vzc2lvbkluZGV4IjowfSx7ImtleSI6Im9wZW5laHJCYXNlVXJsIiwidmFsdWUiOiJodHRwczovL3Jlc3QuZWhyc2NhcGUuY29tL3Jlc3Qvb3BlbmVoci92MSIsImVuYWJsZWQiOnRydWUsInNlc3Npb25WYWx1ZSI6Imh0dHBzOi8vcmVzdC5laHJzY2FwZS5jb20vcmVzdC9vcGVuZWhyL3YxIiwic2Vzc2lvbkluZGV4IjoxfSx7ImtleSI6ImVocnNjYXBlQmFzZVVybCIsInZhbHVlIjoiaHR0cHM6Ly9yZXN0LmVocnNjYXBlLmNvbS9yZXN0L3YxIiwiZW5hYmxlZCI6dHJ1ZSwic2Vzc2lvblZhbHVlIjoiaHR0cHM6Ly9yZXN0LmVocnNjYXBlLmNvbS9yZXN0L3YxIiwic2Vzc2lvbkluZGV4IjoyfSx7ImtleSI6ImFjY291bnROYW1lIiwidmFsdWUiOiJESENXIHRyYWluaW5nIiwiZW5hYmxlZCI6dHJ1ZSwic2Vzc2lvblZhbHVlIjoiREhDVyB0cmFpbmluZyIsInNlc3Npb25JbmRleCI6M30seyJrZXkiOiJVc2VybmFtZSIsInZhbHVlIjoid2FsZXMtdHJhaW5pbmciLCJlbmFibGVkIjp0cnVlLCJzZXNzaW9uVmFsdWUiOiJ3YWxlcy10cmFpbmluZyIsInNlc3Npb25JbmRleCI6NH0seyJrZXkiOiJQYXNzd29yZCIsInZhbHVlIjoid2FsZXMtdHJhaW5pbmciLCJlbmFibGVkIjp0cnVlLCJzZXNzaW9uVmFsdWUiOiJ3YWxlcy10cmFpbmluZyIsInNlc3Npb25JbmRleCI6NX0seyJrZXkiOiJjb21taXR0ZXJOYW1lIiwidmFsdWUiOiJEciBGcmFua2UiLCJlbmFibGVkIjp0cnVlLCJzZXNzaW9uVmFsdWUiOiJEciBGcmFua2UiLCJzZXNzaW9uSW5kZXgiOjZ9LHsia2V5IjoicGF0aWVudE5hbWUiLCJ2YWx1ZSI6Ikl2b3IgQ294IiwiZW5hYmxlZCI6dHJ1ZSwic2Vzc2lvblZhbHVlIjoiSXZvciBDb3giLCJzZXNzaW9uSW5kZXgiOjd9LHsia2V5Ijoic3ViamVjdElkIiwidmFsdWUiOiI5OTk5OTk5MDAwIiwiZW5hYmxlZCI6dHJ1ZSwic2Vzc2lvblZhbHVlIjoiOTk5OTk5OTAwMCIsInNlc3Npb25JbmRleCI6OH0seyJrZXkiOiJuaHNOdW1iZXIiLCJ2YWx1ZSI6Ijk5OTk5OTkwMDAiLCJlbmFibGVkIjp0cnVlLCJzZXNzaW9uVmFsdWUiOiI5OTk5OTk5MDAwIiwic2Vzc2lvbkluZGV4Ijo5fSx7ImtleSI6InN1YmplY3ROYW1lc3BhY2UiLCJ2YWx1ZSI6InVrX25oc19uaHNfbnVtYmVyIiwiZW5hYmxlZCI6dHJ1ZSwic2Vzc2lvblZhbHVlIjoidWtfbmhzX25oc19udW1iZXIiLCJzZXNzaW9uSW5kZXgiOjEwfSx7ImtleSI6ImVocklkIiwidmFsdWUiOiIiLCJlbmFibGVkIjp0cnVlLCJzZXNzaW9uVmFsdWUiOiJjZDU4OGUxMS05MjdmLTQwNWEtYmNjMy05YzU1YmQ0YmJkYmUiLCJzZXNzaW9uSW5kZXgiOjExfSx7ImtleSI6InBhcnR5SWQiLCJ2YWx1ZSI6IiIsImVuYWJsZWQiOnRydWUsInNlc3Npb25WYWx1ZSI6IiIsInNlc3Npb25JbmRleCI6MTJ9LHsia2V5IjoidGVtcGxhdGVJZCIsInZhbHVlIjoiIiwiZW5hYmxlZCI6dHJ1ZSwic2Vzc2lvblZhbHVlIjoiTWFsbnV0cml0aW9uIHVuaXZlcnNhbCBzY3JlZW5pbmcgdG9vbCIsInNlc3Npb25JbmRleCI6MTN9LHsia2V5IjoiY29tcG9zaXRpb25JZCIsInZhbHVlIjoiIiwiZW5hYmxlZCI6dHJ1ZSwic2Vzc2lvblZhbHVlIjoiIiwic2Vzc2lvbkluZGV4IjoxNH0seyJrZXkiOiJxdWVyeVN0cmluZyIsInZhbHVlIjoiIiwiZW5hYmxlZCI6dHJ1ZSwidHlwZSI6ImFueSIsInNlc3Npb25WYWx1ZSI6IlNFTEVDVCBjL3VpZC92YWx1ZSBhcyBjb21wb3NpdGlvblVpZCwgYy9jb21wb3Nlci9uYW1lIGFzIGF1dGhvciwgYy9jb250ZXh0L3N0YXJ0X3RpbWUvdmFsdWUgYXMgZGF0ZVJlY29yZGVkLC4uLiIsInNlc3Npb25JbmRleCI6MTV9XQ==)'